#!/Users/unterbee/anaconda/bin/python
import atomic.adas as adas

atomic_data = './adas_data'
elements_years = [('iron', 89)]

db = adas.OpenAdas()

for element, year in elements_years:
    res = db.search_adf11(element, year)

    for r in res:
        print r[1]
        db.fetch(r, atomic_data)
