#!/usr/bin/env python
import atomic.adas as adas

atomic_data = './adas_data'
elements_years = [('lithium', 96), ('carbon', 96),
                  ('argon', 89),   ('neon', 96), ('nitrogen', 96)]

db = adas.OpenAdas()

for element, year in elements_years:
    res = db.search_adf11(element, year)

    for r in res:
        print r[1]
        db.fetch(r, atomic_data)

for element, year in elements_years:
    res = db.search_adf15(element)

    for r in res:
        print r[1]
        db.fetch(r, atomic_data)
